#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'

cookbook 'tomcat',
  :git => 'git@github.com:intere/tomcat.git',
  :ref => 'v0.15.12'

cookbook 'apache2',
  :git => 'git@github.com:onehealth-cookbooks/apache2.git',
  :ref => 'v1.10.2'

