# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Box Info
  config.vm.box = "centos-6.4-chef"
  config.vm.hostname = "web-server"

  # Port NATs
  config.vm.network :forwarded_port, guest: 80, host: 31080
  config.vm.network :forwarded_port, guest: 443, host: 31443
  # Temporary (debugging) NATs:
  config.vm.network :forwarded_port, guest: 8081, host: 31081


  Vagrant.configure("2") do |config|
    config.vm.provision "shell", inline: "cp /vagrant/config/hosts /etc/hosts"
  end


  # Provisioning (via Chef)
  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = [ "cookbooks" ]
    #chef.add_recipe "apache2"
    #chef.add_recipe "apache2::mod_ssl"
    #chef.add_recipe "java"
    #chef.add_recipe "tomcat"
    chef.add_recipe "appserver"
  end
end

