# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "Ubuntu-Server-12.04"
  config.vm.box_url = "http://goo.gl/8kWkm"
  config.vm.provision "shell", path: "provision.sh"

  # Port NATs
  config.vm.network :forwarded_port, guest: 80, host: 29080
  config.vm.network :forwarded_port, guest: 443, host: 29443
end


