

Vagrant.configure(2) do |config|

  # Port NATs
  # config.vm.network :forwarded_port, guest: 80, host: 30080
  # config.vm.network :forwarded_port, guest: 443, host: 30443

  # Temporary (debugging) NATs:
  config.vm.network :forwarded_port, guest: 8080, host: 30080
  config.vm.network :forwarded_port, guest: 8081, host: 30081
  config.vm.network :forwarded_port, guest: 8443, host: 30043


  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box_url = "https://oss-binaries.phusionpassenger.com/vagrant/boxes/latest/ubuntu-14.04-amd64-vbox.box"
  config.vm.box = "ubuntu-14.04-amd64-vbox"

  config.vm.define :web_server do | web_server_config |
    # config.vm.provision "shell", inline: "mkdir -p /etc/tomcat6; cp /vagrant/config/keystore/keystore.jks /etc/tomcat6;"

    web_server_config.vm.provision "chef_solo" do | chef |

      chef.formatter = ENV.fetch("CHEF_FORMAT", "null").downcase.to_sym
      chef.log_level = ENV.fetch("CHEF_LOG", "info").downcase.to_sym

      chef.cookbooks_path = [ "cookbooks" ]
      chef.add_recipe "appserver"
    end
  end

end
